### ISSUE TITLE
JavaScript error caused by mixed content block on website

### ISSUE THREAD

**Issue by DavidMoraisFerreira** [cmarqu/hikebikemap-website#3]
Hi,

When attempting to open https://hikebikemap.org/, loading Leaflet via http://cdn.leafletjs.com/leaflet-0.7/leaflet.js fails due to a mixed content block.

Edit: I just noticed the closed issue #2, has there been any change?

**Comment by cmarqu** [comment]
The tile hosting does not exist anymore, and doesn't have a replacement, so unfortunately, hikebikemap is dead.

**Comment by DavidMoraisFerreira** [comment]
Thank you for the quick reply :) 

Wouldn't it make sense to take the website offline then? This would avoid confusing users looking for online maps.

**Comment by grischard** [comment]
It does work on http at http://hikebikemap.org, but you mean that the tiles don't get updated anymore?
